name: Python CI

on:
  pull_request:
    branches:
      - main
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip, build, and wheel
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Install package (PEP 517)
        run: |
          pip install .
      - name: Run tests
        run: |
          pytest workshop/upgraded/guachi/tests
